name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@main
        with:
          node-version: 16
      - name: see directory
        run: ls
      - name: install dependencies
        run: yarn install
      - name: build
        run: yarn build